######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 20 14:20:14 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug
INCLUDEPATH += .

# Input
HEADERS += datamodel.h resource.h
SOURCES += datamodel.cpp main.cpp
RESOURCES += images.qrc
