# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aiecg_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import *
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AIECG_UIClass(object):
    def setupUi(self, AIECG_UIClass):
        AIECG_UIClass.setObjectName(_fromUtf8("AIECG_UIClass"))
        AIECG_UIClass.setEnabled(True)
        AIECG_UIClass.resize(1136, 837)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AIECG_UIClass.sizePolicy().hasHeightForWidth())
        AIECG_UIClass.setSizePolicy(sizePolicy)
        AIECG_UIClass.setDocumentMode(False)
        self.centralWidget = QtGui.QWidget(AIECG_UIClass)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_3.setMargin(11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAutoFillBackground(False)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.centralWidget)
        self.tableWidget.setStyleSheet("selection-background-color:lightblue;")
        self.tableWidget.horizontalScrollBar().setStyleSheet("QScrollBar{background:transparent;height:10px}"
                                                             "QScrollBar::handle{background:lightgray; border:2px solid transparent; border-radius:5px;}"
                                                             "QScrollBar::handle:hover{background:gray;}"
                                                             "QScrollBar::sub-line{background:transparent;}"
                                                             "QScrollBar::add-line{background:transparent;}")
        self.tableWidget.verticalScrollBar().setStyleSheet("QScrollBar{background:transparent; width: 10px;}"
                                                           "QScrollBar::handle{background:lightgray; border:2px solid transparent; border-radius:5px;}"
                                                           "QScrollBar::handle:hover{background:gray;}"
                                                           "QScrollBar::sub-line{background:transparent;}"
                                                           "QScrollBar::add-line{background:transparent;}")
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.tableWidget.setFrameShape(QFrame.NoFrame)
        self.tableWidget.horizontalHeader().setClickable(False)
        self.tableWidget.setMinimumSize(QtCore.QSize(242, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(242, 16777215))
        self.tableWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setRowCount(40)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.greenBtnLabel = QtGui.QLabel(self.centralWidget)
        self.greenBtnLabel.setEnabled(False)
        self.greenBtnLabel.setMaximumSize(QtCore.QSize(41, 41))
        self.greenBtnLabel.setStyleSheet(_fromUtf8("image: url(:/AIECG_UI/AIECG_UI/button_green.png);"))
        self.greenBtnLabel.setText(_fromUtf8(""))
        self.greenBtnLabel.setObjectName(_fromUtf8("greenBtnLabel"))
        self.horizontalLayout.addWidget(self.greenBtnLabel)
        self.redBtnLabel = QtGui.QLabel(self.centralWidget)
        self.redBtnLabel.setEnabled(False)
        self.redBtnLabel.setMaximumSize(QtCore.QSize(41, 41))
        self.redBtnLabel.setStyleSheet(_fromUtf8("image: url(:/AIECG_UI/button_red.png);\n"
"image: url(:/AIECG_UI/AIECG_UI/button_red.png);"))
        self.redBtnLabel.setText(_fromUtf8(""))
        self.redBtnLabel.setObjectName(_fromUtf8("redBtnLabel"))
        self.horizontalLayout.addWidget(self.redBtnLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.PRTaxesLabel = QtGui.QLabel(self.centralWidget)
        self.PRTaxesLabel.setObjectName(_fromUtf8("PRTaxesLabel"))
        self.gridLayout.addWidget(self.PRTaxesLabel, 4, 0, 1, 1)
        self.QTLineEdit = QtGui.QLineEdit(self.centralWidget)
        self.QTLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QTLineEdit.sizePolicy().hasHeightForWidth())
        self.QTLineEdit.setSizePolicy(sizePolicy)
        self.QTLineEdit.setObjectName(_fromUtf8("QTLineEdit"))
        self.gridLayout.addWidget(self.QTLineEdit, 3, 1, 1, 1)
        self.PRTaxesLineEdit = QtGui.QLineEdit(self.centralWidget)
        self.PRTaxesLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PRTaxesLineEdit.sizePolicy().hasHeightForWidth())
        self.PRTaxesLineEdit.setSizePolicy(sizePolicy)
        self.PRTaxesLineEdit.setObjectName(_fromUtf8("PRTaxesLineEdit"))
        self.gridLayout.addWidget(self.PRTaxesLineEdit, 4, 1, 1, 1)
        self.QRSdurLineEdit = QtGui.QLineEdit(self.centralWidget)
        self.QRSdurLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QRSdurLineEdit.sizePolicy().hasHeightForWidth())
        self.QRSdurLineEdit.setSizePolicy(sizePolicy)
        self.QRSdurLineEdit.setObjectName(_fromUtf8("QRSdurLineEdit"))
        self.gridLayout.addWidget(self.QRSdurLineEdit, 2, 1, 1, 1)
        self.PRintLineEdit = QtGui.QLineEdit(self.centralWidget)
        self.PRintLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PRintLineEdit.sizePolicy().hasHeightForWidth())
        self.PRintLineEdit.setSizePolicy(sizePolicy)
        self.PRintLineEdit.setObjectName(_fromUtf8("PRintLineEdit"))
        self.gridLayout.addWidget(self.PRintLineEdit, 1, 1, 1, 1)
        self.PRintLabel = QtGui.QLabel(self.centralWidget)
        self.PRintLabel.setObjectName(_fromUtf8("PRintLabel"))
        self.gridLayout.addWidget(self.PRintLabel, 1, 0, 1, 1)
        self.QTLabel = QtGui.QLabel(self.centralWidget)
        self.QTLabel.setObjectName(_fromUtf8("QTLabel"))
        self.gridLayout.addWidget(self.QTLabel, 3, 0, 1, 1)
        self.QRSdurLabel = QtGui.QLabel(self.centralWidget)
        self.QRSdurLabel.setObjectName(_fromUtf8("QRSdurLabel"))
        self.gridLayout.addWidget(self.QRSdurLabel, 2, 0, 1, 1)
        self.VentRateLabel = QtGui.QLabel(self.centralWidget)
        self.VentRateLabel.setObjectName(_fromUtf8("VentRateLabel"))
        self.gridLayout.addWidget(self.VentRateLabel, 0, 0, 1, 1)
        self.VentRateLineEdit = QtGui.QLineEdit(self.centralWidget)
        self.VentRateLineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VentRateLineEdit.sizePolicy().hasHeightForWidth())
        self.VentRateLineEdit.setSizePolicy(sizePolicy)
        self.VentRateLineEdit.setObjectName(_fromUtf8("VentRateLineEdit"))
        self.gridLayout.addWidget(self.VentRateLineEdit, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.heart2Label = QtGui.QLabel(self.centralWidget)
        self.heart2Label.setEnabled(True)
        self.heart2Label.setMaximumSize(QtCore.QSize(211, 231))
        self.heart2Label.setStyleSheet(_fromUtf8("image: url(:/AIECG_UI/AIECG_UI/heart2.png);"))
        self.heart2Label.setText(_fromUtf8(""))
        self.heart2Label.setObjectName(_fromUtf8("heart2Label"))
        self.horizontalLayout_4.addWidget(self.heart2Label)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setMargin(11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.heart1Label = QtGui.QLabel(self.centralWidget)
        self.heart1Label.setEnabled(True)
        self.heart1Label.setMaximumSize(QtCore.QSize(211, 241))
        self.heart1Label.setStyleSheet(_fromUtf8("image: url(:/AIECG_UI/heart1.jpg);\n"
"image: url(:/AIECG_UI/AIECG_UI/heart1.png);"))
        self.heart1Label.setText(_fromUtf8(""))
        self.heart1Label.setObjectName(_fromUtf8("heart1Label"))
        self.horizontalLayout_7.addWidget(self.heart1Label)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 7)
        self.verticalLayout.setStretch(3, 7)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 4)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.layoutWidget = QtGui.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.layoutWidget.raise_()
        AIECG_UIClass.setCentralWidget(self.centralWidget)

        self.retranslateUi(AIECG_UIClass)
        QtCore.QMetaObject.connectSlotsByName(AIECG_UIClass)

    def retranslateUi(self, AIECG_UIClass):
        AIECG_UIClass.setWindowTitle(_translate("AIECG_UIClass", "AIECG_UI", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("AIECG_UIClass", "1", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("AIECG_UIClass", "2", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("AIECG_UIClass", "3", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("AIECG_UIClass", "4", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("AIECG_UIClass", "5", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("AIECG_UIClass", "6", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("AIECG_UIClass", "7", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("AIECG_UIClass", "8", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("AIECG_UIClass", "10", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AIECG_UIClass", "Name", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AIECG_UIClass", "Result", None))
        self.PRTaxesLabel.setText(_translate("AIECG_UIClass", "P-R-T axes:", None))
        self.QTLineEdit.setText(_translate("AIECG_UIClass", "330/428 ms", None))
        self.PRTaxesLineEdit.setText(_translate("AIECG_UIClass", "62 -90 5", None))
        self.QRSdurLineEdit.setText(_translate("AIECG_UIClass", "90 ms", None))
        self.PRintLineEdit.setText(_translate("AIECG_UIClass", "136 ms", None))
        self.PRintLabel.setText(_translate("AIECG_UIClass", "PR int:", None))
        self.QTLabel.setText(_translate("AIECG_UIClass", "QT/QTc:", None))
        self.QRSdurLabel.setText(_translate("AIECG_UIClass", "QRS dur:", None))
        self.VentRateLabel.setText(_translate("AIECG_UIClass", "Vent rate:", None))
        self.VentRateLineEdit.setText(_translate("AIECG_UIClass", "101 BPM", None))

import aiecg_ui_rc
